package com.example.PersonalAccounting.entity.enums;

public enum TransactionCategory {
    CLOTHES_AND_SHOES, GIFTS, ENTERTAINMENT_AND_LEISURE, FINANCIAL_SERVICES, EDUCATION, DWELLING, EXPENSES_FOR_ANIMALS,
    TRANSPORT, FOOD_AND_DRINKS, CHARITY, EXPENSES_FOR_CHILDREN, HEALTH_AND_MEDICINE, OTHER
}
